import type { Metadata } from 'next'
import { Header } from '../_components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function MainLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Header />
      <main className="mt-24">{children}</main>
    </>
  )
}
