// export const stacks = [
//   { id: 'angular', label: 'Angular' },
//   { id: 'arduino', label: 'Arduino' },
//   { id: 'aws', label: 'AWS' },
//   { id: 'bun', label: 'Bun' },
//   { id: 'cloudflare', label: 'Cloudflare' },
//   { id: 'css', label: 'CSS' },
//   { id: 'cypress', label: 'Cypress' },
//   { id: 'docker', label: 'Docker' },
//   { id: 'express', label: 'Express' },
//   { id: 'firebase', label: 'Firebase' },
//   { id: 'flutter', label: 'Flutter' },
//   { id: 'git', label: 'Git' },
//   { id: 'go', label: 'Go' },
//   { id: 'graphql', label: 'GraphQL' },
//   { id: 'html', label: 'HTML' },
//   { id: 'js', label: 'JavaScript' },
//   { id: 'jest', label: 'Jest' },
//   { id: 'mongodb', label: 'MongoDB' },
//   { id: 'mysql', label: 'MySQL' },
//   { id: 'nestjs', label: 'NestJS' },
//   { id: 'nextjs', label: 'Next.js' },
//   { id: 'nginx', label: 'Nginx' },
//   { id: 'nodejs', label: 'Node.js' },
//   { id: 'npm', label: 'npm' },
//   { id: 'nuxtjs', label: 'Nuxt.js' },
//   { id: 'pinia', label: 'Pinia' },
//   { id: 'pnpm', label: 'pnpm' },
//   { id: 'postgres', label: 'PostgreSQL' },
//   { id: 'prisma', label: 'Prisma' },
//   { id: 'rabbitmq', label: 'RabbitMQ' },
//   { id: 'react', label: 'React' },
//   { id: 'redux', label: 'Redux' },
//   { id: 'sass', label: 'Sass' },
//   { id: 'styledcomponents', label: 'Styled Components' },
//   { id: 'supabase', label: 'Supabase' },
//   { id: 'svelte', label: 'Svelte' },
//   { id: 'tailwind', label: 'Tailwind CSS' },
//   { id: 'threejs', label: 'Three.js' },
//   { id: 'ts', label: 'TypeScript' },
//   { id: 'vercel', label: 'Vercel' },
//   { id: 'vite', label: 'Vite' },
//   { id: 'vitest', label: 'Vitest' },
//   { id: 'vue', label: 'Vue.js' },
//   { id: 'vuetify', label: 'Vuetify' },
//   { id: 'yarn', label: 'Yarn' },
// ]

export const stacks = [
  { id: 'ableton', label: 'Ableton' },
  { id: 'activitypub', label: 'ActivityPub' },
  { id: 'actix', label: 'Actix' },
  { id: 'adonis', label: 'Adonis' },
  { id: 'ae', label: 'AE' },
  { id: 'aiscript', label: 'AIScript' },
  { id: 'alpinejs', label: 'Alpine.js' },
  { id: 'anaconda', label: 'Anaconda' },
  { id: 'androidstudio', label: 'Android Studio' },
  { id: 'angular', label: 'Angular' },
  { id: 'ansible', label: 'Ansible' },
  { id: 'apollo', label: 'Apollo' },
  { id: 'apple', label: 'Apple' },
  { id: 'appwrite', label: 'Appwrite' },
  { id: 'arch', label: 'Arch' },
  { id: 'arduino', label: 'Arduino' },
  { id: 'astro', label: 'Astro' },
  { id: 'atom', label: 'Atom' },
  { id: 'au', label: 'AU' },
  { id: 'autocad', label: 'AutoCAD' },
  { id: 'aws', label: 'AWS' },
  { id: 'azul', label: 'Azul' },
  { id: 'azure', label: 'Azure' },
  { id: 'babel', label: 'Babel' },
  { id: 'bash', label: 'Bash' },
  { id: 'bevy', label: 'Bevy' },
  { id: 'bitbucket', label: 'Bitbucket' },
  { id: 'blender', label: 'Blender' },
  { id: 'bootstrap', label: 'Bootstrap' },
  { id: 'bsd', label: 'BSD' },
  { id: 'bun', label: 'Bun' },
  { id: 'c', label: 'C' },
  { id: 'cs', label: 'C#' },
  { id: 'cpp', label: 'C++' },
  { id: 'crystal', label: 'Crystal' },
  { id: 'cassandra', label: 'Cassandra' },
  { id: 'clion', label: 'CLion' },
  { id: 'clojure', label: 'Clojure' },
  { id: 'cloudflare', label: 'Cloudflare' },
  { id: 'cmake', label: 'CMake' },
  { id: 'codepen', label: 'CodePen' },
  { id: 'coffeescript', label: 'CoffeeScript' },
  { id: 'css', label: 'CSS' },
  { id: 'cypress', label: 'Cypress' },
  { id: 'd3', label: 'D3' },
  { id: 'dart', label: 'Dart' },
  { id: 'debian', label: 'Debian' },
  { id: 'deno', label: 'Deno' },
  { id: 'devto', label: 'Dev.to' },
  { id: 'discord', label: 'Discord' },
  { id: 'bots', label: 'Bots' },
  { id: 'discordjs', label: 'Discord.js' },
  { id: 'django', label: 'Django' },
  { id: 'docker', label: 'Docker' },
  { id: 'dotnet', label: '.NET' },
  { id: 'dynamodb', label: 'DynamoDB' },
  { id: 'eclipse', label: 'Eclipse' },
  { id: 'elasticsearch', label: 'Elasticsearch' },
  { id: 'electron', label: 'Electron' },
  { id: 'elixir', label: 'Elixir' },
  { id: 'elysia', label: 'Elysia' },
  { id: 'emacs', label: 'Emacs' },
  { id: 'ember', label: 'Ember' },
  { id: 'emotion', label: 'Emotion' },
  { id: 'express', label: 'Express' },
  { id: 'fastapi', label: 'FastAPI' },
  { id: 'fediverse', label: 'Fediverse' },
  { id: 'figma', label: 'Figma' },
  { id: 'firebase', label: 'Firebase' },
  { id: 'flask', label: 'Flask' },
  { id: 'flutter', label: 'Flutter' },
  { id: 'forth', label: 'Forth' },
  { id: 'fortran', label: 'Fortran' },
  { id: 'gamemakerstudio', label: 'GameMaker Studio' },
  { id: 'gatsby', label: 'Gatsby' },
  { id: 'gcp', label: 'GCP' },
  { id: 'git', label: 'Git' },
  { id: 'github', label: 'GitHub' },
  { id: 'githubactions', label: 'GitHub Actions' },
  { id: 'gitlab', label: 'GitLab' },
  { id: 'gmail', label: 'Gmail' },
  { id: 'gherkin', label: 'Gherkin' },
  { id: 'go', label: 'Go' },
  { id: 'gradle', label: 'Gradle' },
  { id: 'godot', label: 'Godot' },
  { id: 'grafana', label: 'Grafana' },
  { id: 'graphql', label: 'GraphQL' },
  { id: 'gtk', label: 'GTK' },
  { id: 'gulp', label: 'Gulp' },
  { id: 'haskell', label: 'Haskell' },
  { id: 'haxe', label: 'Haxe' },
  { id: 'haxeflixel', label: 'HaxeFlixel' },
  { id: 'heroku', label: 'Heroku' },
  { id: 'hibernate', label: 'Hibernate' },
  { id: 'html', label: 'HTML' },
  { id: 'htmx', label: 'HTMX' },
  { id: 'idea', label: 'IDEA' },
  { id: 'ai', label: 'AI' },
  { id: 'instagram', label: 'Instagram' },
  { id: 'ipfs', label: 'IPFS' },
  { id: 'java', label: 'Java' },
  { id: 'js', label: 'JavaScript' },
  { id: 'jenkins', label: 'Jenkins' },
  { id: 'jest', label: 'Jest' },
  { id: 'jquery', label: 'jQuery' },
  { id: 'kafka', label: 'Kafka' },
  { id: 'kali', label: 'Kali' },
  { id: 'kotlin', label: 'Kotlin' },
  { id: 'ktor', label: 'Ktor' },
  { id: 'kubernetes', label: 'Kubernetes' },
  { id: 'laravel', label: 'Laravel' },
  { id: 'latex', label: 'LaTeX' },
  { id: 'less', label: 'Less' },
  { id: 'linkedin', label: 'LinkedIn' },
  { id: 'linux', label: 'Linux' },
  { id: 'lit', label: 'Lit' },
  { id: 'lua', label: 'Lua' },
  { id: 'md', label: 'MD' },
  { id: 'mastodon', label: 'Mastodon' },
  { id: 'materialui', label: 'Material UI' },
  { id: 'matlab', label: 'Matlab' },
  { id: 'maven', label: 'Maven' },
  { id: 'mint', label: 'Mint' },
  { id: 'misskey', label: 'Misskey' },
  { id: 'mongodb', label: 'MongoDB' },
  { id: 'mysql', label: 'MySQL' },
  { id: 'neovim', label: 'Neovim' },
  { id: 'nestjs', label: 'NestJS' },
  { id: 'netlify', label: 'Netlify' },
  { id: 'nextjs', label: 'Next.js' },
  { id: 'nginx', label: 'Nginx' },
  { id: 'nim', label: 'Nim' },
  { id: 'nix', label: 'Nix' },
  { id: 'nodejs', label: 'Node.js' },
  { id: 'notion', label: 'Notion' },
  { id: 'npm', label: 'npm' },
  { id: 'nuxtjs', label: 'Nuxt.js' },
  { id: 'obsidian', label: 'Obsidian' },
  { id: 'ocaml', label: 'OCaml' },
  { id: 'octave', label: 'Octave' },
  { id: 'opencv', label: 'OpenCV' },
  { id: 'openshift', label: 'OpenShift' },
  { id: 'p5js', label: 'p5.js' },
  { id: 'perl', label: 'Perl' },
  { id: 'ps', label: 'PS' },
  { id: 'php', label: 'PHP' },
  { id: 'phpstorm', label: 'PhpStorm' },
  { id: 'pinia', label: 'Pinia' },
  { id: 'pkl', label: 'PKL' },
  { id: 'plan9', label: 'Plan9' },
  { id: 'planetscale', label: 'PlanetScale' },
  { id: 'pnpm', label: 'pnpm' },
  { id: 'postgres', label: 'PostgreSQL' },
  { id: 'postman', label: 'Postman' },
  { id: 'powershell', label: 'PowerShell' },
  { id: 'pr', label: 'PR' },
  { id: 'prisma', label: 'Prisma' },
  { id: 'processing', label: 'Processing' },
  { id: 'prometheus', label: 'Prometheus' },
  { id: 'pug', label: 'Pug' },
  { id: 'pycharm', label: 'PyCharm' },
  { id: 'py', label: 'Python' },
  { id: 'pytorch', label: 'PyTorch' },
  { id: 'qt', label: 'Qt' },
  { id: 'r', label: 'R' },
  { id: 'rabbitmq', label: 'RabbitMQ' },
  { id: 'rails', label: 'Rails' },
  { id: 'raspberrypi', label: 'Raspberry Pi' },
  { id: 'react', label: 'React' },
  { id: 'reactivex', label: 'ReactiveX' },
  { id: 'redhat', label: 'Red Hat' },
  { id: 'redis', label: 'Redis' },
  { id: 'redux', label: 'Redux' },
  { id: 'regex', label: 'Regex' },
  { id: 'remix', label: 'Remix' },
  { id: 'replit', label: 'Replit' },
  { id: 'rider', label: 'Rider' },
  { id: 'robloxstudio', label: 'Roblox Studio' },
  { id: 'rocket', label: 'Rocket' },
  { id: 'rollupjs', label: 'Rollup.js' },
  { id: 'ros', label: 'ROS' },
  { id: 'ruby', label: 'Ruby' },
  { id: 'rust', label: 'Rust' },
  { id: 'sass', label: 'Sass' },
  { id: 'spring', label: 'Spring' },
  { id: 'sqlite', label: 'SQLite' },
  { id: 'stackoverflow', label: 'Stack Overflow' },
  { id: 'styledcomponents', label: 'Styled Components' },
  { id: 'sublime', label: 'Sublime' },
  { id: 'supabase', label: 'Supabase' },
  { id: 'scala', label: 'Scala' },
  { id: 'sklearn', label: 'scikit-learn' },
  { id: 'selenium', label: 'Selenium' },
  { id: 'sentry', label: 'Sentry' },
  { id: 'sequelize', label: 'Sequelize' },
  { id: 'sketchup', label: 'SketchUp' },
  { id: 'solidity', label: 'Solidity' },
  { id: 'solidjs', label: 'SolidJS' },
  { id: 'svelte', label: 'Svelte' },
  { id: 'svg', label: 'SVG' },
  { id: 'swift', label: 'Swift' },
  { id: 'symfony', label: 'Symfony' },
  { id: 'tailwind', label: 'Tailwind CSS' },
  { id: 'tauri', label: 'Tauri' },
  { id: 'tensorflow', label: 'TensorFlow' },
  { id: 'terraform', label: 'Terraform' },
  { id: 'threejs', label: 'Three.js' },
  { id: 'twitter', label: 'Twitter' },
  { id: 'ts', label: 'TypeScript' },
  { id: 'ubuntu', label: 'Ubuntu' },
  { id: 'unity', label: 'Unity' },
  { id: 'unreal', label: 'Unreal' },
  { id: 'v', label: 'V' },
  { id: 'vala', label: 'Vala' },
  { id: 'vercel', label: 'Vercel' },
  { id: 'vim', label: 'Vim' },
  { id: 'visualstudio', label: 'Visual Studio' },
  { id: 'vite', label: 'Vite' },
  { id: 'vitest', label: 'Vitest' },
  { id: 'vscode', label: 'Visual Studio Code' },
  { id: 'vscodium', label: 'VSCodium' },
  { id: 'vue', label: 'Vue.js' },
  { id: 'vuetify', label: 'Vuetify' },
  { id: 'wasm', label: 'WebAssembly' },
  { id: 'webflow', label: 'Webflow' },
  { id: 'webpack', label: 'Webpack' },
  { id: 'webstorm', label: 'WebStorm' },
  { id: 'windicss', label: 'Windi CSS' },
  { id: 'windows', label: 'Windows' },
  { id: 'wordpress', label: 'WordPress' },
  { id: 'workers', label: 'Workers' },
  { id: 'xd', label: 'XD' },
  { id: 'yarn', label: 'Yarn' },
  { id: 'yew', label: 'Yew' },
  { id: 'zig', label: 'Zig' },
]
